// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title AgentDelegation
 * @notice Handles capital delegation to agents with performance-based returns
 * @dev Users deposit capital, which is delegated to agents based on their track record
 */

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "@openzeppelin/contracts/security/Pausable.sol";
import "./AgentRegistry.sol";

contract AgentDelegation is Ownable, ReentrancyGuard, Pausable {
    
    struct Delegation {
        address delegator;
        address agentAddress;
        uint256 capitalAmount;
        uint256 delegatedAt;
        uint256 accumulatedReturns; // accumulated returns
        bool active;
    }

    struct AgentFees {
        uint256 performanceFee; // basis points (e.g., 2000 = 20%)
        uint256 managementFee; // basis points (e.g., 100 = 1%)
    }

    IERC20 public stablecoin; // e.g., USDC
    AgentRegistry public agentRegistry;
    
    mapping(address => mapping(address => Delegation)) public delegations; // delegator => agent => delegation
    mapping(address => AgentFees) public agentFees;
    mapping(address => uint256) public agentTotalReturns;
    mapping(address => uint256) public delegatorTotalDeposits;
    
    uint256 public platformFeeBasisPoints = 500; // 5%
    uint256 public treasuryBalance;

    event DelegationCreated(address indexed delegator, address indexed agent, uint256 amount);
    event DelegationWithdrawn(address indexed delegator, address indexed agent, uint256 amount);
    event ReturnsDistributed(address indexed agent, uint256 totalReturns, uint256 timestamp);
    event FeesUpdated(address indexed agent, uint256 performanceFee, uint256 managementFee);

    constructor(address _stablecoin, address _agentRegistry) {
        stablecoin = IERC20(_stablecoin);
        agentRegistry = AgentRegistry(_agentRegistry);
    }

    /**
     * @notice Delegate capital to an agent
     * @param _agentAddress Agent to delegate to
     * @param _amount Amount to delegate
     */
    function delegate(
        address _agentAddress,
        uint256 _amount
    ) external nonReentrant whenNotPaused {
        require(_amount > 0, "Amount must be greater than 0");
        
        // Check if agent exists and is active
        require(agentRegistry.getAgent(_agentAddress).agentAddress != address(0), "Agent not found");
        require(agentRegistry.isAgentActive(_agentAddress), "Agent not active");

        // Transfer stablecoin from delegator to contract
        require(
            stablecoin.transferFrom(msg.sender, address(this), _amount),
            "Transfer failed"
        );

        Delegation storage delegation = delegations[msg.sender][_agentAddress];
        
        if (!delegation.active) {
            delegation.delegator = msg.sender;
            delegation.agentAddress = _agentAddress;
            delegation.delegatedAt = block.timestamp;
            delegation.active = true;
            delegation.capitalAmount = _amount;
            agentRegistry.addDelegator(_agentAddress, msg.sender, _amount);
        } else {
            delegation.capitalAmount += _amount;
            agentRegistry.addDelegator(_agentAddress, msg.sender, _amount);
        }

        delegatorTotalDeposits[msg.sender] += _amount;

        emit DelegationCreated(msg.sender, _agentAddress, _amount);
    }

    /**
     * @notice Withdraw delegation (principal + returns)
     * @param _agentAddress Agent to withdraw from
     */
    function withdraw(address _agentAddress) external nonReentrant {
        Delegation storage delegation = delegations[msg.sender][_agentAddress];
        require(delegation.active, "No active delegation");

        uint256 totalWithdraw = delegation.capitalAmount + delegation.accumulatedReturns;
        require(totalWithdraw > 0, "Nothing to withdraw");

        delegation.active = false;
        delegation.capitalAmount = 0;
        delegation.accumulatedReturns = 0;

        agentRegistry.removeDelegator(_agentAddress, msg.sender, totalWithdraw);

        require(stablecoin.transfer(msg.sender, totalWithdraw), "Transfer failed");

        emit DelegationWithdrawn(msg.sender, _agentAddress, totalWithdraw);
    }

    /**
     * @notice Distribute returns to delegators of an agent (called by oracle)
     * @param _agentAddress Agent to distribute for
     * @param _totalReturns Total returns generated by agent
     */
    function distributeReturns(
        address _agentAddress,
        uint256 _totalReturns
    ) external onlyOwner nonReentrant {
        require(_totalReturns > 0, "Returns must be positive");

        address[] memory delegators = agentRegistry.getDelegators(_agentAddress);
        require(delegators.length > 0, "No delegators");

        // Calculate total delegated capital
        uint256 totalDelegated = 0;
        for (uint256 i = 0; i < delegators.length; i++) {
            totalDelegated += delegations[delegators[i]][_agentAddress].capitalAmount;
        }

        require(totalDelegated > 0, "No capital delegated");

        // Extract fees
        uint256 agentPerformanceFee = (_totalReturns * agentFees[_agentAddress].performanceFee) / 10000;
        uint256 platformFee = (_totalReturns * platformFeeBasisPoints) / 10000;
        uint256 delegatorReturns = _totalReturns - agentPerformanceFee - platformFee;

        treasuryBalance += platformFee;

        // Distribute to delegators proportionally
        for (uint256 i = 0; i < delegators.length; i++) {
            address delegator = delegators[i];
            Delegation storage delegation = delegations[delegator][_agentAddress];

            if (delegation.active && delegation.capitalAmount > 0) {
                uint256 delegatorShare = (delegatorReturns * delegation.capitalAmount) / totalDelegated;
                delegation.accumulatedReturns += delegatorShare;
            }
        }

        agentTotalReturns[_agentAddress] += _totalReturns;
        
        emit ReturnsDistributed(_agentAddress, _totalReturns, block.timestamp);
    }

    /**
     * @notice Set agent fees
     * @param _agentAddress Agent to set fees for
     * @param _performanceFee Performance fee in basis points
     * @param _managementFee Management fee in basis points
     */
    function setAgentFees(
        address _agentAddress,
        uint256 _performanceFee,
        uint256 _managementFee
    ) external {
        address agentManager = agentRegistry.getAgentManager(_agentAddress);
        require(
            agentManager == msg.sender || msg.sender == owner(),
            "Only agent manager or owner"
        );
        require(_performanceFee <= 5000 && _managementFee <= 500, "Fees too high");

        agentFees[_agentAddress] = AgentFees({
            performanceFee: _performanceFee,
            managementFee: _managementFee
        });

        emit FeesUpdated(_agentAddress, _performanceFee, _managementFee);
    }

    // View Functions

    function getDelegation(address _delegator, address _agentAddress) 
        external 
        view 
        returns (Delegation memory) 
    {
        return delegations[_delegator][_agentAddress];
    }

    function getTotalDelegated(address _delegator) external view returns (uint256) {
        return delegatorTotalDeposits[_delegator];
    }

    function getAgentTotalReturns(address _agentAddress) external view returns (uint256) {
        return agentTotalReturns[_agentAddress];
    }
}
